### ISSUE TITLE
Package C++ version of rerun-sdk? 

### ISSUE THREAD

**Issue by traversaro** [conda-forge/rerun-sdk-feedstock#18]
### Comment:

Hello @conda-forge/rerun-sdk, thanks a lot for working/maintaining rerun-sdk! I work in a research institute, and I am quite interested in getting people in my group to try rerun-sdk, in particular the upcoming C++ version. However, I would like to point them to a conda-forge package to install, to streamline the installation process. There is any plan to add the C++ package here, either as part of the `rerun-sdk` package or a separate output?

**Comment by traversaro** [comment]
I just realized that at the moment https://github.com/rerun-io/rerun/blob/main/rerun_cpp/CMakeLists.txt does not have any logic for install or generation of CMake config files, so probably before packaging it here that is necessary.

**Comment by ruben-arts** [comment]
That should definitely be coming to the conda packages!

**Comment by jleibs** [comment]
Thanks for the pointers, @traversaro

**Comment by traversaro** [comment]
xref: https://github.com/rerun-io/rerun/issues/4579 .

**Comment by traversaro** [comment]
Given https://github.com/conda-forge/rerun-sdk-feedstock/pull/30#issuecomment-1975106069 I was thinking on packaging the C++ version of the SDK as its own separate feedstock, anyone has any specific opinion on this?

**Comment by traversaro** [comment]
> Given [#30 (comment)](https://github.com/conda-forge/rerun-sdk-feedstock/pull/30#issuecomment-1975106069) I was thinking on packaging the C++ version of the SDK as its own separate feedstock, anyone has any specific opinion on this?

Done in https://github.com/conda-forge/staged-recipes/pull/25648 .
